image: node:latest

stages:
  - test

playwright_tests:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: manual
    paths:
      - playwright-report/
    expire_in: 1 day
  only:
    - main